services:
  - type: web
    name: file-board
    env: docker
    plan: free
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: ADMIN_USER
        value: admin
      - key: ADMIN_PASS
        generateValue: true
      - key: REDIS_URL
        fromService:
          type: redis
          name: fileboard-redis
          property: connectionString
      - key: MIN_FREE_SPACE_GB
        value: 1

  - type: redis
    name: fileboard-redis
    plan: free
    ipAllowList: [] # Internal only

databases:
  - name: snapdoc-db
    databaseName: snapdoc
    user: snapdoc
    plan: free